[dev]
address = "localhost"
port = "8080"
workers = 4

[dev.database]
adapter = "mysql"
name = "test"
pool = 5

[prod]
address = "0.0.0.0"
port = "443"

[prod.database]
adapter = "mysql"
name = "prod"
pool = 5
